/**
contact: software@cbica.upenn.edu
Copyright (c) 2018 University of Pennsylvania. All rights reserved.
Use of this source code is governed by license located in license file: https://github.com/CBICA/DeepMRSegApp/blob/main/LICENSE
**/
#ifndef DeepMRSegMediator_h
#define DeepMRSegMediator_h

// The following header file is generated by CMake and thus it's located in
// the build directory. It provides an export macro for classes and functions
// that you want to be part of the public interface of your module.
#include <MitkCbicaDeepMRSegExports.h>

#include <mitkImage.h>

#include <itkInvertIntensityImageFilter.h>

#include <usGetModuleContext.h>
#include <mitkIPythonService.h>
#include <usModuleContext.h>


/** \class DeepMRSegMediator
 *  \brief Mediator for Python based DeepMRSeg application
 */
class MITKCBICADEEPMRSEG_EXPORT DeepMRSegMediator
{
	/** \brief  This class is basically a mediator for Python based DeepMRSeg application.
		 * It also sets up the necessary python service and environment
	*/
public:
	DeepMRSegMediator();

	~DeepMRSegMediator() {}

	// ITK-filter-like functions
	void SetT1Image(mitk::Image::Pointer T1ImagePtr);
	void SetFlairImage(mitk::Image::Pointer FlImagePtr);

	void Update();
	mitk::Image::Pointer GetOutput();

	void RunSampleScript();

	// Utility functions for working with python
	bool IsOkayToRun();
	void PassArgsToPython(std::vector<std::string> args); // convenience function
	bool ChangeWorkingDirectory(std::string newWorkingDirectoryPath);

protected:
	mitk::Image::Pointer m_InputPtr_T1, m_InputPtr_Flair;
	mitk::Image::Pointer m_LastOutput;

	us::ServiceReference<mitk::IPythonService> m_PythonServiceRef;
	mitk::IPythonService* m_PythonService;

	// path to our located python files
	std::string pythonFilesDirPath;
	bool pythonFilesDirFound;


	void RegisterResourceDir(std::string resourceDirPath);
	void RegisterPackageDir(std::string packageDirPath);

	std::string LocatePythonFileDir();
};

#endif // ! DeepMRSegMediator_h
