set(Plugin-Name "DeepMRSeg")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "CBICA, University of Pennsylvania")
set(Plugin-ContactAddress "https://www.med.upenn.edu/cbica/")
set(Require-Plugin upenn.cbica.deepmrseg.ui)
